name: JobWatcherApi

on:
  push:
    branches:
      - cicisetup

env:
  AZURE_WEBAPP_NAME: jobwatch-api
  AZURE_WEBAPP_PACKAGE_PATH: backend/JobWatcher.Api/publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: jobwatch-api_group
  AZURE_APIM_SERVICENAME: JobWatcherApiapi
  AZURE_APIM_API_ID: JobWatcherApi
  AZURE_APIM_APPSERVICEURL: https://jobwatch-api-g6a3cjenesbna5gv.canadacentral-01.azurewebsites.net
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 5.6.3
  SWASHBUCKLE_DOTNET_CORE_VERSION: 3.1.x
  API_IMPORT_SPECIFICATION_PATH: backend/JobWatcher.Api/publish/swagger.json
  API_IMPORT_DLL: backend/JobWatcher.Api/bin/Release/net8.0/JobWatcher.Api.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: backend/JobWatcher.Api
  ASPNETCORE_ENVIRONMENT: Development

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Setup SwashBuckle .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.SWASHBUCKLE_DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build
        run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Test
        run: dotnet test --no-build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Publish
        run: dotnet publish --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        working-directory: ${{ env.WORKING_DIRECTORY }}

      # --- Swashbuckle CLI setup and verification ---
      - name: Install Swashbuckle CLI .NET Global Tool
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version ${{ env.SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION }}

      - name: Verify Swagger CLI Installation
        run: |
          $env:PATH += ";C:\Users\runneradmin\.dotnet\tools"
          swagger --version
        shell: pwsh

      - name: Generate Open API Specification Document
        run: |
          $env:PATH += ";C:\Users\runneradmin\.dotnet\tools"
          swagger tofile --output "${{ env.API_IMPORT_SPECIFICATION_PATH }}" "${{ env.API_IMPORT_DLL }}" "${{ env.API_IMPORT_VERSION }}" --startupAssembly "${{ env.API_IMPORT_DLL }}"
        shell: pwsh
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.JobWatcherApiapi_SPN }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.jobwatch_api_E56F }}

      - name: Import API into Azure API Management
        run: az apim api import --path "${{ env.AZURE_APIM_RESOURCE_PATH }}" --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" --service-name "${{ env.AZURE_APIM_SERVICENAME }}" --api-id "${{ env.AZURE_APIM_API_ID }}" --service-url "${{ env.AZURE_APIM_APPSERVICEURL }}" --specification-path "${{ env.API_IMPORT_SPECIFICATION_PATH }}" --specification-format OpenApi --subscription-required false
        shell: pwsh

      - name: Logout
        run: az logout
